services:
  clove-bot:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/usr/src/app/logs
      - ./data:/usr/src/app/data  # Add this line for persistent ticket data
    networks:
      - clove-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  clove-network:
    driver: bridge

volumes:
  logs:
  data: 